---
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    documentclass: scrartcl
    papersize: letter
    pdf-engine: xelatex
    fontsize: 9pt
    geometry:
      - margin=0.5in
      - heightrounded
    include-in-header:
      - preamble.tex
execute:
  warning: false
  echo: false
  message: false
  eval: true
---
```{r}
#| name: setup
#| include: false
#| message: false
#| eval: true

knitr::opts_chunk$set(
fig.path = "figs/",
fig.width = 7.252,
fig.height = 4,
comment = "#>",
fig.retina = 3
)

source("functions.R")

# Store IDs
gscholar_id <- "iNdNU5QAAAAJ"
gscholar_page <- paste0("https://scholar.google.com/citations?user=", gscholar_id)

# Google Scholar text
text_gs <- invisible(gscholar_stats(url = gscholar_page))
```

\par\centering{\Large{\textbf{Darwin Del Castillo Fernandez, M.D.}}}
\vspace{-5pt}
\par\centering{\textit{Address:} 4545 8th Ave NE, Seattle, WA 98105}
\vspace{-5pt}
\par\centering{\textit{Mobile:} +1 (206) 605 5077 (USA; WhatsApp) | +51 965 006 311 (Peru)}
\vspace{-5pt}
\par\centering{\textit{Email:} ddelcastillo.f@gmail.com}
\vspace{-5pt}
\par\centering{\textit{LinkedIn:} \href{https://www.linkedin.com/in/darwin-del-castillo-md/}{https://www.linkedin.com/in/darwin-del-castillo-md/}}
\rule{\textwidth}{0.5pt}
\vspace{-10pt}

\section{\underline{Summary}}
\justifying{Medical doctor and global health scientist with extensive experience bridging the gap between epidemiological methods and healthcare data science. I am committed to transforming early-life health outcomes through innovative research and data-driven solutions. I have collaborated with a diversity of global health institutions and managing research teams that translates data findings into actionable public health information.}

\section{\underline{Professional Experience}}

\begin{longtable}{p{14cm}>{\raggedleft\arraybackslash}p{4cm}}

\textbf{Research Intern} & \textbf{July 2024 - Present} \\
\multicolumn{2}{p{18cm}}{\textbf{Clinical Informatics Team, Institute for Health Metrics and Evaluation}} \\
\multicolumn{2}{p{18cm}}{\textbf{University of Washington, Seattle (USA)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Estimating population attributable fractions and standardized mortality ratios for socially excluded groups, i.e., people experiencing imprisonment, homelessness, and substance use disorders, in high-income countries.
\item Analyzing data from public sources and a previously published systematic review using Bayesian and Monte Carlo methods to estimate the overlap proportion between socially excluded groups in high-income countries.
\item Collaborating in a NIH research proposal to estimate the disease burden for socially excluded groups in high-income countries.
\end{itemize}
} \\

\textbf{Research Assistant} & \textbf{Jun 2024 - Present} \\
\multicolumn{2}{p{18cm}}{\textbf{Department of Global Health}} \\
\multicolumn{2}{p{18cm}}{\textbf{University of Washington, Seattle (USA)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize} 
\item Designing a systematic review protocol for mapping potential indicators for the implementation of mental health policy in data-limited settings.
\item Collaborating in the design of a mixed-method study protocol to assess the effectiveness of implementation strategies for pediatric burn care in a Peruvian healthcare setting.
\item Engaging with stakeholders from multiple countries to planning the future implementation of our research findings.
\end{itemize}
} \\

\textbf{Research Assistant}  & \textbf{Sep 2023 - Dec 2023} \\
\multicolumn{2}{p{18cm}}{\textbf{Health Population Research Center, Department of Health Systems and Population Health}} \\
\multicolumn{2}{p{18cm}}{\textbf{University of Washington, Seattle (USA)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize} 
\item Conducted on-phone interviews for the second post-survey assessment of the ReOpening Schools Safely and Educating Youth Study (ROSSEY Study).
\item Performed preliminary statistical analyses for the Outreach, Engagement, and Recruitment module of the ADRC Clinical Core Study project.
\item Coordinated engagement activities with Latinx communities from King County (WA) to increase participation in the ADRC Clinical Core Study project.
\end{itemize}
} \\

\textbf{Research Consultant} & \textbf{Jan 2023 - Jan 2024} \\
\multicolumn{2}{p{18cm}}{\textbf{Health Technology Assessment Direction, Health Technology Assessment and Research Institute}} \\
\multicolumn{2}{p{18cm}}{\textbf{Social Security Health System, Lima (Peru)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Assessed the health benefits of purchasing pharmaceutical products through a systematic evaluation of the effectiveness and economic impact
\item Conducted systematic reviews of oncologic and immunosuppressant drugs regarding efficacy and economic impact.
\item Performed budget impact analyses of introducing new pharmacological products into the Social Security System.
\end{itemize}
} \\

\textbf{Research Assistant} & \textbf{Mar 2019 - Aug 2023}\\
\multicolumn{2}{p{18cm}}{\textbf{CRONICAS Center of Excellence in Chronic Diseases}} \\
\multicolumn{2}{p{18cm}}{\textbf{Universidad Peruana Cayetano Heredia, Lima (Peru)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Conducted semi-structured qualitative interviews for the NIHR-UK-funded project, with researchers from Universidad Peruana Cayetano Heredia, Imperial College London, and the University of Oxford
\item Performed a systematic review with collaborators from Latin America, USA, UK, Europe, and Africa to develop a core set of outcomes for designing multimorbidity clinical trials.
\item Coordinated fieldwork data collection with community health workers across diverse Peruvian regions.
\item Analyzed data from a longitudinal Brazilian cohort to assess the impact of preterm birth on body composition and blood pressure in children at age 22.
\end{itemize}
} \\

\textbf{Clinical Sub-investigator} & \textbf{Mar 2022 - Mar 2023} \\
\multicolumn{2}{p{18cm}}{\textbf{Clinical Research Unit}} \\
\multicolumn{2}{p{18cm}}{\textbf{Via Libre Association, Lima (Peru)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Performed clinical procedures and assessed clinical trial participants from the HVTN and the HPTN networks.
\item Completed clinical trial documentation for ensuring adherence to Good Clinical Practices.
\item Participated and organized activities to increase outreach and participant retention tailored for members of the queer community.
\end{itemize}
} \\

\end{longtable}

\section{\underline{Education}}

\begin{longtable}{p{14cm}>{\raggedleft\arraybackslash}p{4cm}}

\textbf{Master - Public Health/Global Health} & \textbf{Sep 2023 – June 2025} \\
\multicolumn{2}{p{18cm}}{\textbf{University of Washington, Seattle (USA)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Analyzed the cost-effectiveness of a salt substitute intervention to reduce five-year incidence of hypertension in six villages in northern Peru.
\item Assessed barriers and facilitators for the implementation of pediatric burn injuries care in secondary and tertiary healthcare centers in Peru.
\end{itemize}
} \\

\textbf{Certificate - Clinical Research} & \textbf{Sep 2021 – Apr 2022} \\
\multicolumn{2}{p{18cm}}{\textbf{Universidad Peruana Cayetano Heredia, Lima (Peru)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Mastered statistical methods utilized in clinical research, including regression modelling, survival analysis, and meta-analysis of both observational and experimental studies. 
\end{itemize}
} \\

\textbf{Medical Doctor (MD)} & \textbf{Mar 2013 – Dec 2020} \\
\multicolumn{2}{p{18cm}}{\textbf{Universidad Nacional Mayor de San Marcos, Lima (Peru)}} \\
\multicolumn{2}{p{18cm}}{%
\begin{itemize}
\item Organized communications between university authorities and students. Class president.
\item Participated in social accountability activities with a Tuna musical group.
\end{itemize}
} \\

\end{longtable}

\section{\underline{Leadership and Service}}
%%%Transform this section in a long table
\begin{itemize}
  \item Trainee Advisory Committee Member, Consortium of Universities for Global Health (CUGH), USA: Collaborate with international co-trainees to address global health challenges and provide student perspectives on global health issues such as COVID-19, racial disparities, climate change, and research involvement of global health students (Jan 2025-current).
  \item Emeritus member and External Advisor, \href{https://cem.edu.pe/adiecs/}{Association for the Development of Student's Research in Health Sciences (ADIECS)}, Peru: Peruvian student association funded in 2008 by students from the Universidad Nacional Mayor de San Marcos with the aim of developing capacity of both hard (e.g., epidemiological study designs, data analysis) and soft skills (e.g., teamwork communication, problem-solving) for biomedical underserved students (Mar 2014-current).
\end{itemize}

\section{\underline{Skills}}

\begin{justify}
\textbf{Computer and programming skills:} Advanced skills in STATA and R for statistical analysis, data visualization, decision-making analyses. Intermediate skills for Bayesian statistics, Monte Carlo methods, and machine learning algorithms. Certificates in data management, causal inference, and machine learning applied to healthcare. \\
Intermediate skills in Dedoose and Atlas.ti for qualitative data analysis, thematic coding, and content analysis. \\
Competencies in Microsoft Office Suite (Word, PowerPoint, Excel), G*Power, and REDCap.\\
\textbf{Languages:} Spanish (native), English (fluent), French (basic) \\
\textbf{Academic Publications:} 4 scientific publications (\href{`r gscholar_page`}{See full list}). Analysis and interpretation of results for lay audiences. \\
\end{justify}

